In [8]:
import numpy as np
from pprint import pprint

In [23]:
# panels = np.array([[0,0],[1,0],[1,1],[0,1]])
panels = np.array([[0,0],[1,0],[1,1]])

XYZ2 = panels  # Coordinates of end point of panel
XYZ1 = np.roll(panels, 1, axis=0)  # Coordinates of the next end point of panel
# print(f"{XYZ2=}, {XYZ1=}")
diff = XYZ1 - XYZ2
# print(f"{diff=}")

# Controlpoints point at 3/4 of panel. #pcp  = 0.5*( XYZ1 + XYZ2 )[:,:2]
pcp = XYZ2 + diff * 0.75
# Vortex point at 1/4 of panel.
vp = XYZ2 + diff * 0.25
print(f"{pcp=}, \n {vp=}")
p = pcp[:, np.newaxis, :]

print(f"{pcp[:, np.newaxis, :]=}")
print(np.broadcast_to(p,(3,3,2)))
# print(f"{pcp[:,:, np.newaxis]=}")

print(f"{vp[np.newaxis,:, :]=}")
print(np.broadcast_to(vp[np.newaxis,:, :],(3,3,2)))

# pprint(pcp)
#pb is the angle to the normal of the panel
pb = np.arctan2(diff[:, 1], diff[:, 0]) + np.pi / 2
# print(f"{pcp.shape=},{vp.shape=},{pb.shape=}")
# print(f"{pcp[:, np.newaxis, :].shape=}, {vp[np.newaxis, :, :].shape=}")
# Calculate K matrix
pcp_diff = pcp[:, np.newaxis, :] - vp[np.newaxis, :, :]
print(f"{pcp_diff=}")


pcp=array([[0.75, 0.75],
       [0.25, 0.  ],
       [1.  , 0.25]]), 
 vp=array([[0.25, 0.25],
       [0.75, 0.  ],
       [1.  , 0.75]])
pcp[:, np.newaxis, :]=array([[[0.75, 0.75]],

       [[0.25, 0.  ]],

       [[1.  , 0.25]]])
[[[0.75 0.75]
  [0.75 0.75]
  [0.75 0.75]]

 [[0.25 0.  ]
  [0.25 0.  ]
  [0.25 0.  ]]

 [[1.   0.25]
  [1.   0.25]
  [1.   0.25]]]
vp[np.newaxis,:, :]=array([[[0.25, 0.25],
        [0.75, 0.  ],
        [1.  , 0.75]]])
[[[0.25 0.25]
  [0.75 0.  ]
  [1.   0.75]]

 [[0.25 0.25]
  [0.75 0.  ]
  [1.   0.75]]

 [[0.25 0.25]
  [0.75 0.  ]
  [1.   0.75]]]
pcp_diff=array([[[ 0.5 ,  0.5 ],
        [ 0.  ,  0.75],
        [-0.25,  0.  ]],

       [[ 0.  , -0.25],
        [-0.5 ,  0.  ],
        [-0.75, -0.75]],

       [[ 0.75,  0.  ],
        [ 0.25,  0.25],
        [ 0.  , -0.5 ]]])
